# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Notes

  target 'Notes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'NotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Notes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Notes-tvOS

  target 'Notes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
